### ISSUE TITLE
test_env_pour doesn't show a connected full motion

### ISSUE THREAD

**Issue by giesth39** [kelvin34501/OakInk2-SimEnv-IsaacGym#1]
Hello, I ran  the test_env_pour.py, but i've got segmented motions in different tables in Isaac Gym.
Is this the right result? it seems different from README example.

![Screenshot from 2024-07-05 14-19-35](https://github.com/kelvin34501/OakInk2-SimEnv-IsaacGym/assets/174769290/13c4242a-f9e6-4b6e-81ad-f46fd7ab5d49)

![Screenshot from 2024-07-05 14-20-46](https://github.com/kelvin34501/OakInk2-SimEnv-IsaacGym/assets/174769290/21ba3802-b6f3-490d-9e63-7a12d991b8ea)

**Comment by kelvin34501** [comment]
This is the right result. The observation and reward functions in `test_env_pour.py` are empty placeholders; no action will be applied in the example script.

The animation in README is an example of the demo trajectory provided as part of the assets. These trajectories are directly transferred from the interactions in OakInk2 dataset; they are kinematically noisy and probably dynamically implausible. Utilizing these trajectories (including the hands and objects) to synthesize physically plausible hand-object interactions is part of the challenge.

Visit the [wiki page](https://github.com/kelvin34501/OakInk2-SimEnv-IsaacGym/wiki/Observing-and-Understanding-Hands-in-Action-(HANDS-Workshop@ECCV2024)) for more information.

Hope this reply helps you. If you have any further questions or need further explanations feel free to ask here.
