### ISSUE TITLE
when will MF-MDM be released?

### ISSUE THREAD

**Issue by wuxiaofei01** [kelvin34501/OakInk2-SimEnv-IsaacGym#4]
Hello, first of all, thank you for your work, which is a great contribution to the entire community. I read in the paper that you use a **MF-MDM** to solve **primitive tasks**. I would like to ask if you have r**elevant code**?

**Comment by wuxiaofei01** [comment]
I found that the Oakink2 dataset has not been released yet. Is there a plan to release it later? Including pipeline

**Comment by kelvin34501** [comment]
Topics related to OakInk2 dataset should go to [this place](https://github.com/oakink/OakInk2-PreviewTool). You can reopen the issue there.
